import { Link } from 'react-router-dom'
import { Users, Mic, AlertTriangle, Plus, ChevronRight, Activity } from 'lucide-react'
import { patients, predictions, recordings } from '../mocks'
import { StatCard } from '../components/StatCard'
import { PageHeader, Card, Badge, Button } from '../components/ui'

export function DashboardPage() {
  const flaggedCount = predictions.filter(
    (item) => item.label === 'murmur' || item.label === 'abnormal'
  ).length

  return (
    <div className="space-y-6">
      <PageHeader
        title="Good morning, Dr. Nair"
        subtitle="Here is the real-time auscultation summary from your clinical workspace."
        action={
          <Link to="/record">
            <Button variant="primary" icon={<Plus className="h-4 w-4" />}>
              New recording
            </Button>
          </Link>
        }
      />

      {/* Stats Summary Grid */}
      <section className="grid gap-4 sm:grid-cols-3">
        <StatCard
          label="Active Patients"
          value={patients.length}
          hint="Registered patient records"
          icon={<Users className="h-5 w-5 text-brand-700" />}
          trend={{ value: '+2 this week', isUp: true }}
        />
        <StatCard
          label="Captured Recordings"
          value={recordings.length}
          hint="Auscultation tracks saved"
          icon={<Mic className="h-5 w-5 text-brand-700" />}
          trend={{ value: '100% processed', isUp: true }}
        />
        <StatCard
          label="Flagged Results"
          value={flaggedCount}
          hint="Require immediate clinician review"
          icon={<AlertTriangle className="h-5 w-5 text-amber-600" />}
          trend={{ value: `${flaggedCount} pending`, isUp: false }}
        />
      </section>

      {/* Recent Activity List */}
      <Card>
        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
          <div>
            <h2 className="font-bold text-slate-900 flex items-center gap-2">
              <Activity className="h-4 w-4 text-brand-600" />
              Recent Auscultations & Inference Signals
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Latest predictions generated by the AI acoustic engine.
            </p>
          </div>
          <Link
            to="/patients"
            className="inline-flex items-center gap-1 text-xs font-semibold text-brand-700 hover:text-brand-800"
          >
            View all patients <ChevronRight className="h-3.5 w-3.5" />
          </Link>
        </div>

        <div className="divide-y divide-slate-100 mt-1">
          {recordings.slice(0, 5).map((recording) => {
            const result = predictions.find((item) => item.recordingId === recording.id)
            const patient = patients.find((item) => item.id === recording.patientId)

            const badgeVariant =
              result?.label === 'murmur' || result?.label === 'abnormal'
                ? 'warning'
                : result?.label === 'normal'
                ? 'success'
                : 'neutral'

            return (
              <Link
                to={`/patients/${recording.patientId}`}
                key={recording.id}
                className="flex items-center justify-between py-3.5 px-2 rounded-lg transition-colors hover:bg-slate-50"
              >
                <div>
                  <p className="font-bold text-slate-900 text-sm">
                    {patient?.firstName} {patient?.lastName}
                  </p>
                  <p className="text-xs text-slate-500 capitalize">
                    {recording.auscultationSite} Position · {recording.durationSeconds}s duration · Recorded {new Date(recording.recordedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <Badge variant={badgeVariant} pulse={badgeVariant === 'warning'}>
                    {result
                      ? `${result.label} (${Math.round(result.confidence * 100)}%)`
                      : recording.status}
                  </Badge>
                  <ChevronRight className="h-4 w-4 text-slate-300" />
                </div>
              </Link>
            )
          })}
        </div>
      </Card>
    </div>
  )
}
